version: '3.2'

services:
  gscout:
    build:
      context: .
      dockerfile: Dockerfile
      cache_from:
        - stono/gscout 
    volumes:
      - ./results:/opt/gscout/Report Output
      - ./home:/root
